name: rotinafit
description: "Lembretes + acompanhamento do corpo num lugar sÃ³."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  google_mobile_ads: ^4.0.0
  in_app_purchase: ^3.1.13
  fl_chart: ^0.66.0
  intl: ^0.19.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
